disabled_rules:
  # Disable insistence on parameter and returns documentation. "Writing a great
  # summary is more important than leveraging keywords." See
  # https://github.com/realm/SwiftLint/issues/284 for discussion.
  - valid_docs
