language: objective-c
xcode_project: HypertextApplicationLanguage.xcodeproj
xcode_scheme: HypertextApplicationLanguage
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
